# Your Solution
version: "3.7"

services:
  book-catalog:
    image: book-catalog:1
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "4001:80"
    environment:
      - PORT=80
      - DATABASE_URL=postgresql://oliver_722_part3_user:aoN2388BKPqP3JABpQYThRzot8FoYSN4@dpg-criodclumphs73cnp5cg-a.oregon-postgres.render.com/oliver_722_part3
    restart: "no"

  inventory-management:
    image: inventory-management:1
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "4002:81"
    environment:
      - PORT=81
      - DATABASE_URL=postgresql://oliver_722_part3_user:aoN2388BKPqP3JABpQYThRzot8FoYSN4@dpg-criodclumphs73cnp5cg-a.oregon-postgres.render.com/oliver_722_part3
    restart: "no"
